language: python
python:
  - "3.7"
before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
install:
  - poetry install -v
script:
  - poetry run pytest --cov=command_log tests
