[tool.poetry]
name = "django-command-log"
version = "0.1.0"
description = "Django management command auditing app"
authors = ["YunoJuno <code@yunojuno.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.1"
psycopg2-binary = "^2.8"

[tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
coverage = "^4.5"
dj-database-url = "^0.5.0"
isort = "^4.3"
pylint = "^2.4"
pylint-django = "^2.0"
pytest = "^3.0"
pytest-cov = "^2.7"
pytest-django = "^3.5"
safety = "^1.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
