[tool.poetry]
name = "django-command-log"
version = "0.1.0"
description = "Django management command auditing app"
authors = ["YunoJuno <code@yunojuno.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.2"
psycopg2-binary = "*"

[tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
dj-database-url = "^0.5.0"
isort = "*"
pylint = "*"
pytest = "^3.0"
pytest-django = "^3.5"
coverage = "^4.5"
pytest-cov = "^2.7"
pylint-django = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
